name: ping (Every 30 Days)

on:
  schedule:
    - cron: "0 0 1 * *"   # every month on day 1 @ midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Update Script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: node updateProduct.ts
