name: Daily Scheduled Update

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:       

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Call backend update endpoint
        run: curl -X GET "https://your-domain.com/cron/update?key=${{ secrets.CRON_KEY }}"
